version: '3.8'

services:
  apache-php:
    build: ./apache-php
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./apache-php:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=users_db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_HOST: db  # Es importante asegurarse de que la variable MYSQL_HOST sea correcta
    ports:
      - "8081:80"
    depends_on:
      - db
